### ISSUE TITLE
unable to compile with openssl-1.1.0

### ISSUE THREAD

**Issue by computersalat** [alagoutte/shrew#1]
I think we are running into this issue:
https://github.com/openssl/openssl/issues/962

Can you try to fix please ?
Thank you :-)

**Comment by alagoutte** [comment]
Hi,

What issue do you have ?

It is only (my) copy of Shrew Client...

**Comment by computersalat** [comment]
sorry ... completely forgot about this.
It is obsolete now. Switched to `wireguard`.
